DROP TABLE IF EXISTS RESERVATION;
CREATE TABLE RESERVATION(
    RESERVATIONID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    VEHICLEID INT,
    PICKUPDATE DATE,
    RETURNDATE DATE,
    RESERVATIONDATE DATE,
    CUSTOMERID INT,
    STATUS TEXT
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESERVATION;
DROP TABLE IF EXISTS RENT;
CREATE TABLE RENT(
    RENTID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    RESERVATIONID INT,
    TOTALRENTDAY INT,
    STATUS TEXT
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RENT;
DROP TABLE IF EXISTS VEHICLE;
CREATE  TABLE VEHICLE(
    VEHICLEID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    BRAND TEXT,
    TYPE TEXT,
    MODEL TEXT,
    YEAR TEXT,
    SEATQUANTITY TEXT,
    FUELTYPE TEXT,
    PLATENUMBER TEXT,
    CONDITION TEXT,
    DAILYPRICE DOUBLE
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VEHICLE;
DROP TABLE IF EXISTS PERSON;
CREATE  TABLE PERSON(
    FIRSTNAME TEXT,
    LASTNAME TEXT,
    ADDRESS TEXT,
    PHONENUMBER TEXT,
    NATIONALITY TEXT,
    PERSONID INT PRIMARY KEY AUTO_INCREMENT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;
DROP TABLE IF EXISTS CUSTOMER;
CREATE  TABLE CUSTOMER(
    CUSTOMERID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DRIVERLICENSENO TEXT,
    PERSONID INT,
    RESERVATIONID INT
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER;

					